Log dependent packages in version error case. (#646)
* Log dependent packages in version error case.

For version errors, calculate and log dependent packages. Previously,
version errors were checked before the entirety of dependencies were
calculated. This gives  an iterative, annoying flavour to
fixing dependency errors:

1. Bump required version of express.
2. Get error on acl:
  Error: acl depends on express but has a lower required TypeScript version.
3. Bump required version of acl.
4. Get error on api-error-handler:
  Error: api-error-handler depends on express but has a lower required TypeScript version.
5. Bump required version of api-error-handler, etc etc.

Now an error thrown from check-require-version runs getAffectedPackages
and logs the dependents it finds. Then it re-throws the error. The above
process is now:

1. Bump required version of express.
2. Get error on acl, api-error-handler, etc etc.
3. Bump required version on all these packages.

The additional output looks like this:

Running: git rev-parse --verify master
06ddc1ccad76a7a5f766328a2fd0244bbfb06adf
Running: git diff master --name-status
M	types/express/index.d.ts
Testing 1 changed packages: express
Testing 234 dependent packages:acl,actions-on-google,api-error-handler,...

* Remove unused expression and fix lint