fix: only directories are valid type roots
When working on OSX, a `.DS_Store` file gets automatically generated in directories opened in Finder. This breaks:
```
➜  DefinitelyTyped git:(master) ✗ npm test

> definitely-typed@0.0.1 test /Users/joscha/Development/DefinitelyTyped
> node node_modules/types-publisher/bin/tester/test.js --run-from-definitely-typed --nProcesses 1

Clean data
Clean logs
Clean output
# Typing Publish Report Summary
Started at Wed, 07 Jun 2017 22:23:34 GMT
Found 3160 typings folders in /Users/joscha/Development/DefinitelyTyped/types
Error: Package name `.DS_Store` should be strictly lowercase
    at Object.<anonymous> (/Users/joscha/Development/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:17:9)
    at Generator.next (<anonymous>)
```